/*
 * generated by Xtext 2.25.0
 */
package l3IAProjectHTML.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("l3IAProjectHTML/parser/antlr/internal/InternalMyDsl.tokens");
	}
}
